docker cp ./prestashop/html/admin123 duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/app duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/bin duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/classes duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/config duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/controllers duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/docs duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/download duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/img duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/js duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/localization duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/mails duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/modules duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/override duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/pdf duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/src duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/themes duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/tools duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/translations duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/upload duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/vendor duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/webservice duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/.htaccess duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/autoload.php duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/composer.lock duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/error500.html duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/images.inc.php duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/index.php duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/init.php duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/INSTALL.txt duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/robots.txt duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/LICENSES duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/Makefile duzybiceps-presta:/var/www/html
docker cp ./prestashop/html/phpstan.neon.dist duzybiceps-presta:/var/www/html