version: "3.4"
services:
  be_187229:
    image: 10.40.71.55:5000/be_187229_duzybiceps:latest
    depends_on:
      - admin-mysql_db
    container_name: be_187229
    ports:
      - 17228:80
      - 17229:443
    environment:
      - DB_SERVER=admin-mysql_db
      - DB_NAME=BE_187229
      - DB_USER=root
      - DB_PASSWD=student
      - DB_PORT=3306
      - PS_INSTALL_AUTO=0
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin123
      - PS_FOLDER_INSTALL=install123
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=s187229@student.pg.edu.pl
      - ADMIN_PASSWD=duzybiceps
    volumes: 
      - be_187229_duzybiceps:/var/www/html
    networks:
      - admin-mysql_default

volumes:
  be_187229_duzybiceps: