version: "3.4"
services:
  # baza danych do prestashopa
  duzybiceps-db:
    image: mysql:latest
    container_name: duzybiceps-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
    networks:
      - prestashop-net

  # inicjalizacja bazy danych za pomoca innego kontenera
  duzybiceps-init:
    image: mysql:latest
    depends_on:
      - "duzybiceps-db"
    container_name: duzybiceps-init
    volumes: 
      - './mysql/database_dump.sql:/home/database_dump.sql'
      - './mysql/presta_db_config.sql:/home/presta_db_config.sql'
    command:
    - bash
    - -c
    - |
      sleep 60
      mysql -h duzybiceps-db -uroot -padmin prestashop --skip-column-names -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'prestashop';" > /home/wynik.txt
      chmod +777 /home/wynik.txt
      echo "Checked if database is populated."
      if grep -q "0" /home/wynik.txt; then
        echo "Database not populated, populating it now..."
        mysql -h duzybiceps-db -uroot -padmin prestashop < /home/database_dump.sql
        mysql -h duzybiceps-db -uroot -padmin prestashop < /home/presta_db_config.sql
        echo "Database populated!"
      else
        echo "Database already populated!"
      fi
    networks:
      - prestashop-net

  # sklep
  duzybiceps-presta:
    image: prestashop/prestashop:1.7.8.7 
    depends_on:
      - "duzybiceps-db"
    container_name: duzybiceps-presta
    ports:
      - 8080:80
      - 8443:443
    environment:
      - DB_SERVER=duzybiceps-db
      - DB_NAME=prestashop
      - DB_USER=root
      - DB_PASSWD=admin
      - DB_PORT=3306
      - PS_INSTALL_AUTO=0
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin123
      - PS_FOLDER_INSTALL=install123
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=s187229@student.pg.edu.pl
      - ADMIN_PASSWD=duzybiceps
    links:
      - duzybiceps-db
    volumes: 
      - presta-store-storage:/var/www/html
      - './apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf'
      - './ssl/duzybiceps.crt:/etc/ssl/duzybiceps.crt'
      - './ssl/private/duzybiceps.key:/etc/ssl/private/duzybiceps.key'
    networks:
      - prestashop-net

networks:
  prestashop-net:

volumes:
  presta-db-storage:
  presta-store-storage: