version: "3.4"
services:
  be_187229:
    image: duzybiceps/presta:latest
    ports:
      - 17228:80
      - 17229:443
    environment:
      - DB_SERVER=actina15.maas
      - DB_NAME=BE_187229
      - DB_USER=be_187229
      - DB_PASSWD=abrakadabra
      - DB_PORT=3306
      - PS_INSTALL_AUTO=0
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin123
      - PS_FOLDER_INSTALL=install123
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=s187229@student.pg.edu.pl
      - ADMIN_PASSWD=duzybiceps
    volumes: 
      - be_187229_duzybiceps:/var/www/html
    networks:
      - admin-mysql_default
    deploy:
      replicas: 1

volumes:
  be_187229_duzybiceps:

networks:
  admin-mysql_default:
    external:
      name: admin-mysql_default