<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXlaa0wg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXlaa0wg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXlaa0wg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXlaa0wg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXlaa0wg\appProdProjectContainer([
    'container.build_hash' => 'Xlaa0wg',
    'container.build_id' => '5762a64b',
    'container.build_time' => 1670620664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXlaa0wg');
