<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA11by36\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA11by36/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA11by36.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA11by36\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA11by36\appProdProjectContainer([
    'container.build_hash' => 'A11by36',
    'container.build_id' => 'bf9cfdb0',
    'container.build_time' => 1668709098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA11by36');
