<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSkf65hf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSkf65hf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSkf65hf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSkf65hf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSkf65hf\appProdProjectContainer([
    'container.build_hash' => 'Skf65hf',
    'container.build_id' => '8dab1178',
    'container.build_time' => 1669234941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSkf65hf');
